export const REQUEST_WEATHER = "REQUEST_WEATHER";
export const RECEIVE_WEATHER = "RECEIVE_WEATHER";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_CITIES = "FETCH_CITIES";
export const REQUEST_CITIES = "REQUEST_CITIES";
export const RECEIVE_CITIES = "RECEIVE_CITIES";
export const DELETE_LAST_CITY = "DELETE_LAST_CITY";
export const INCREMENT = "INCREMENT";
